language: node_js
node_js:
 - '6'
script:
 - npm run lint
 - npm run build
 - npm test
before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: typed-bignumber-js.surge.sh
